---
title: "R Happy FUN blog"
output:
  rmdformats::html_clean:
    highlight: kate
---


```{r knitr_init, echo=FALSE, cache=FALSE, message=FALSE}
library(knitr)
library(rmdformats)
library(dplyr)
library(lubridate)
library(stringr)
library(tidyr)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r build_index, include=FALSE}
# recursively list all filenames
site_files <- data_frame(path=list.dirs(path=".", recursive=TRUE, full.names = FALSE))
site_files <- site_files %>% 
  filter(! (path %in% c("","site_libs") | str_detect(path, "_cache"))) %>%
  separate(path, c("parent", "slug", "content"), sep="/", remove=FALSE)

# extract blog entries
blogs <- site_files %>% 
  filter(parent == "blog" & !is.na(slug) & is.na(content)) %>%
  mutate(file_mtime=file.mtime(path), 
         file_pretty_date=floor_date(file_mtime, "days"),
         file_year=year(file_mtime),
         link=paste0("[", file_pretty_date, ": ", slug, "](", path, "/index.html)")) %>%
  arrange(file_mtime)

blogs_to_print <- blogs %>%
  select(file_year, link) %>%
  mutate(link=paste0(" * ", link, "\n")) %>%
  group_by(file_year) %>%
  nest(.key="links")

# TODO add tags
```

```{r list_blogs, results='asis'}

for (r in 1:nrow(blogs_to_print)) {
  cat(paste("##",blogs_to_print$file_year[[r]], "\n\n"))
  cat(paste(unlist(blogs_to_print$links[[r]]), collapse=""), "\n")
}

```

```{r list_tags, results='asis', eval=FALSE}
# TODO

```








